#!/usr/bin/env bash
#
# sync-license-allowlist.sh — regenerate the host-nginx IP allowlist for the
# client-facing licensing endpoints from the api_clients table.
#
# The production vhost restricts POST /api/v1/licenses/(activate|validate|
# deactivate|heartbeat) to known deployment IPs. This script makes the DB the
# source of truth: every active api_client's allowed_ips becomes an `allow`
# line, so provisioning a client with --ips=... is all an operator has to do.
#
# Install (on the VPS, as root):
#   1. Copy this script:      install -m 0755 scripts/sync-license-allowlist.sh /usr/local/bin/
#   2. In the licensing vhost's restricted location block, replace hardcoded
#      `allow ...;` lines with:   include snippets/license-allowlist.conf;
#      (keep `deny all;` and the proxy include in the vhost).
#   3. Cron it:  echo '* * * * * root /usr/local/bin/sync-license-allowlist.sh' \
#                  > /etc/cron.d/license-allowlist
#
# Requires: docker compose stack at COMPOSE_DIR, jq.
set -euo pipefail

COMPOSE_DIR="${COMPOSE_DIR:-/opt/thirdline-license}"
SNIPPET="${SNIPPET:-/etc/nginx/snippets/license-allowlist.conf}"
# Extra IPs always allowed regardless of DB state (e.g. this host's public IP
# for the co-located GRC app when it goes through the public vhost).
STATIC_ALLOW="${STATIC_ALLOW:-95.111.252.235}"

cd "$COMPOSE_DIR"

# Pull every active client's allowed_ips (json array) and flatten to one IP per
# line. Clients with allowed_ips NULL are internet-roaming: they don't get (or
# need) an nginx allow entry only if they call via localhost; public roaming
# clients must have explicit IPs to pass this gate.
ips=$(docker compose exec -T postgres psql -tA \
        -U "$(docker compose exec -T postgres printenv POSTGRES_USER | tr -d '\r')" \
        -d "$(docker compose exec -T postgres printenv POSTGRES_DB | tr -d '\r')" \
        -c "SELECT COALESCE(string_agg(ip, E'\n'), '')
              FROM (SELECT DISTINCT json_array_elements_text(allowed_ips) AS ip
                      FROM api_clients
                     WHERE is_active = true AND allowed_ips IS NOT NULL) t;")

tmp=$(mktemp)
{
    echo "# Generated by sync-license-allowlist.sh — DO NOT EDIT (DB is the source of truth)"
    echo "# $(date -u +%FT%TZ)"
    for ip in $STATIC_ALLOW; do
        echo "allow ${ip};"
    done
    while IFS= read -r ip; do
        [ -n "$ip" ] && echo "allow ${ip};"
    done <<< "$ips"
} > "$tmp"

# Only touch nginx when the set of allow lines actually changed.
if [ -f "$SNIPPET" ] \
   && diff -q <(grep '^allow' "$SNIPPET" | sort) <(grep '^allow' "$tmp" | sort) > /dev/null 2>&1; then
    rm -f "$tmp"
    exit 0
fi

mv "$tmp" "$SNIPPET"
chmod 0644 "$SNIPPET"

if nginx -t > /dev/null 2>&1; then
    systemctl reload nginx
    logger -t license-allowlist "nginx allowlist updated ($(grep -c '^allow' "$SNIPPET") entries)"
else
    logger -t license-allowlist "ERROR: nginx -t failed after allowlist regen; NOT reloading"
    exit 1
fi
